#!/bin/bash
SCRIPT_FOLDER=/home/usadmin/hometasks/task1/ 
SERVER_LIST=$(echo $SCRIPT_FOLDER."client_hosts")
echo SERVER_LIST
ERROR_MESSAGE='0'
LOG_FILE=

if [ -r $SERVER_LIST ]; then
echo "file exists"
#    while IFS='' read -r line || [[ -n "$line" ]]; do
#        echo "Text read from file: $line"
#    done < "$1"
else 
    ERROR_MESSAGE="\r\nThe file containig client hosts list was not found. \r\nAborting. \r\nCheck SERVER_LIST variable in the [$0]\r\n"
fi

echo -e "$ERROR_MESSAGE" 
